apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/argocd-apps
    repoURL: 'https://gitlab.com/freeminions/argocd-app-config.git'
    targetRevision: HEAD

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true