# service
apiVersion: v1
kind: Service
metadata:
  name: gitops-server-service
  namespace: demo
spec:
  selector:
    app: gitops-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30001
---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-server
  namespace: demo
  labels:
    app: gitops-server
# for deployment
spec:
  selector:
    matchLabels:
      app: gitops-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gitops-server
    # for pods
    spec:
      containers:
      - name: gitops-server
        image: cosminbucur/gitops-server:latest
        ports:
        - containerPort: 8081
