# argocd app configuration (k8 manifest file)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-server
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/freeminions/argocd-app-config.git
    targetRevision: HEAD
    path: .
  destination: 
    # local minikube
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    syncOptions:
    # create the namespace if it doesn't exist
    - CreateNamespace=true

    automated:
      # auto sync with git repository 
      selfHeal: true
      prune: true
