apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-server
# for deployment
spec:
  selector:
    matchLabels:
      app: gitops-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gitops-server
    # for pods
    spec:
      containers:
      - name: gitops-server
        image: cosminbucur/gitops-server:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
